#################################### common config : ####################################
spring:
  application:
    name: market
  datasource:
    url: jdbc:mysql://adev.top:3306/adev-account?serverTimezone=UTC
    username: root
    password: 239ea79e9e2a61df
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
  rabbitmq:
    host: adev.top
    port: 5672
    virtual-host: adev_vhost
    username: admin
    password: adev.top
# 应用服务web访问端口
server:
  port: 8091
---
spring:
  profiles: test
# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://adev.top:8761/eureka/,http://adev.top:8762/eureka/
---
spring:
  profiles: dev
# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka/


      