#################################### common config : ####################################
spring:
  application:
    name: market
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/common_account?serverTimezone=UTC
    username: root
    password: sjchen
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  rabbitmq:
    host: adev.top
    port: 5672
    virtual-host: adev_vhost
    username: admin
    password: adev.top
# 应用服务web访问端口
server:
  port: 8091

# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/



      